#
# docker build --tag=stonesteps/linecnt-fedora:latest \
#               --file=/path/to/Dockerfile.fedora \
#                   /path/to/context
#
FROM fedora

#
# Dependencies
#
RUN dnf -y install gcc-c++ make flex gtest-devel
