/*
    linecnt - a source line counting utility

    Copyright (c) 2003-2021, Stone Steps Inc. (www.stonesteps.ca)

    See COPYING and Copyright files for additional licensing and copyright information
*/
#define __CPPLEXER_IMP_CPP

extern "C" {
//
// A Flex scanner generated from cpplexer_scanner.l.
//
// Note that scanners generated by Flex prior to v2.6 will use the
// deprecated `register` keyword and will trigger compiler warnings,
// which may be treated as errors.
//
#include "cpplexer_scanner.inc"
}

#include "cpplexer.h"

///
/// Both file handles are passed to `yyrestart` verbatim.
///
CppFlexLexer::CppFlexLexer(FILE* arg_yyin)
{
   yyrestart(arg_yyin);
}

CppFlexLexer::~CppFlexLexer(void)
{
}

int CppFlexLexer::yylex(void)
{
   return ::yylex();
}

const char *CppFlexLexer::YYText(void)
{
   return yytext;
}
